[tool.poetry]
name = "haiven-cli"
version = "0.3.0"
description = ""
authors = ["Thoughtworks <haiven@thoughtworks.com>"]
readme = "README.md"

[tool.poetry.scripts]
haiven-cli = "haiven_cli.main:cli"

[tool.poetry.dependencies]
python = "^3.12"
beautifulsoup4 = "^4.13.5"
faiss-cpu = "^1.11.0.post1"
langchain = "^0.3.27"
langchain-openai = "^0.3.31"
langchain-community = "^0.3.27"
boto3 = "^1.40.21"
pypdf = "^6.0.0"
pytest = "^8.4.1"
pytest-mock = "^3.14.1"
python-dotenv = "^1.1.1"
tiktoken = "^0.11.0"
typer = "^0.12.5"
typer-cli = "^0.12.5"
typer-slim = "^0.16.1"
typing-extensions = "^4.15.0"
typing-inspect = "^0.9.0"
pytest-cov = "^6.2.1"
toml = "^0.10.2"
pydantic = "^2.11.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["tests/*"]
