[tool.poetry]
name = "haiven-cli"
version = "0.3.0"
description = ""
authors = ["Thoughtworks <haiven@thoughtworks.com>"]
readme = "README.md"

[tool.poetry.scripts]
haiven-cli = "haiven_cli.main:cli"

[tool.poetry.dependencies]
python = "~3.12"
beautifulsoup4 = "^4.14.2"
faiss-cpu = "^1.12.0"
langchain = "^0.3.27"
langchain-openai = "^0.3.35"
langchain-community = "^0.3.30"
boto3 = "^1.40.59"
pypdf = "^6.1.3"
pytest = "^9.0.0"
pytest-mock = "^3.15.1"
python-dotenv = "^1.2.1"
tiktoken = "^0.12.0"
typer = "^0.12.5"
typer-cli = "^0.12.5"
typer-slim = "^0.20.0"
typing-extensions = "^4.15.0"
typing-inspect = "^0.9.0"
pytest-cov = "^7.0.0"
toml = "^0.10.2"
pydantic = "^2.12.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["tests/*"]
