[tool.poetry]
name = "haiven-cli"
version = "0.3.0"
description = ""
authors = ["Thoughtworks <haiven@thoughtworks.com>"]
readme = "README.md"

[tool.poetry.scripts]
haiven-cli = "haiven_cli.main:cli"

[tool.poetry.dependencies]
python = "^3.11"
beautifulsoup4 = "^4.12.3"
faiss-cpu = "^1.8.0.post1"
langchain = "^0.2.6"
langchain-google-genai = "^1.0.7"
langchain-google-vertexai = "^1.0.6"
langchain-openai = "^0.1.13"
langchain-community = "^0.2.6"
pypdf = "^4.2.0"
pytest = "^8.2.2"
pytest-mock = "^3.14.0"
python-dotenv = "^1.0.1"
tiktoken = "^0.7.0"
typer = "^0.12.3"
typer-cli = "^0.12.3"
typer-slim = "^0.12.3"
typing-extensions = "^4.12.2"
typing-inspect = "^0.9.0"
pytest-cov = "^5.0.0"
toml = "^0.10.2"
pydantic = "^2.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["tests/*"]
