[tool.poetry]
name = "teamai-cli"
version = "0.1.0"
description = ""
authors = ["TeamAI <teamai@thoughtworks.com>"]
readme = "README.md"

[tool.poetry.scripts]
teamai-cli = "teamai_cli.main:cli"

[tool.poetry.dependencies]
python = "^3.11"
beautifulsoup4 = "^4.12.3"
faiss-cpu = "^1.8.0"
langchain = "0.1.11"
langchain-google-genai = "^1.0.1"
langchain-google-vertexai = "^0.1.2"
langchain-openai = "^0.1.1"
pypdf = "^4.2.0"
pytest = "^8.1.1"
pytest-mock = "^3.14.0"
python-dotenv = "^1.0.1"
tiktoken = "^0.6.0"
typer = "^0.12.2"
typer-cli = "^0.12.2"
typer-slim = "^0.12.2"
typing-extensions = "^4.11.0"
typing-inspect = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
