[tool.poetry]
name = "haiven"
version = "0.1.0"
description = ""
authors = ["Thoughtworks <haiven@thoughtworks.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
Authlib = "^1.3.1"
boto3 = "^1.34.162"
faiss-cpu = "^1.8.0.post1"
fastapi = "^0.112.0"
google-cloud-aiplatform = "^1.61.0"
gradio = "^4.41.0"
itsdangerous = "^2.2.0"
Jinja2 = "^3.1.4"
langchain = "^0.2.12"
langchain-google-genai = "^1.0.8"
langchain-google-vertexai = "^1.0.8"
langchain-openai = "^0.1.21"
langchain-community = "^0.2.11"
loguru = "^0.7.2"
ollama = "^0.3.1"
openai = "^1.40.3"
pyarrow = "^17.0.0"
pypdf = "^4.3.1"
python-frontmatter = "^1.1.0"
shapely = "^2.0.5"
tiktoken = "^0.7.0"
typing-extensions = "^4.12.2"
typing-inspect = "^0.9.0"
uvicorn = "^0.30.5"
python-dotenv = "^1.0.1"
toml = "^0.10.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-mock = "^3.14.0"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["tests/*"]