[tool.poetry]
name = "haiven"
version = "0.1.0"
description = ""
authors = ["Thoughtworks <haiven@thoughtworks.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
Authlib = "^1.5.1"
boto3 = "^1.37.29"
faiss-cpu = "^1.10.0"
fastapi = "^0.115.11"
google-cloud-aiplatform = "^1.84.0"
itsdangerous = "^2.2.0"
Jinja2 = "^3.1.6"
langchain = "^0.3.20"
langchain-openai = "^0.3.8"
langchain-community = "^0.3.19"
loguru = "^0.7.3"
ollama = "^0.4.7"
openai = "^1.66.2"
pyarrow = "^19.0.1"
pypdf = "^5.3.1"
python-frontmatter = "^1.1.0"
shapely = "^2.0.7"
tiktoken = "^0.9.0"
typing-extensions = "^4.12.2"
typing-inspect = "^0.9.0"
uvicorn = "^0.34.0"
python-dotenv = "^1.0.1"
toml = "^0.10.2"
pillow = "^11.1.0"
python-multipart = "^0.0.20"
litellm = "^1.63.6"
tenacity = "^9.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-mock = "^3.14.0"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["tests/*"]