[tool.poetry]
name = "haiven"
version = "0.1.0"
description = ""
authors = ["Thoughtworks <haiven@thoughtworks.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
Authlib = "^1.3.2"
boto3 = "^1.35.76"
faiss-cpu = "^1.9.0.post1"
fastapi = "^0.115.6"
google-cloud-aiplatform = "^1.74.0"
itsdangerous = "^2.2.0"
Jinja2 = "^3.1.4"
langchain = "^0.3.9"
langchain-openai = "^0.2.11"
langchain-community = "^0.3.9"
loguru = "^0.7.2"
ollama = "^0.4.2"
openai = "^1.56.2"
pyarrow = "^18.1.0"
pypdf = "^5.1.0"
python-frontmatter = "^1.1.0"
shapely = "^2.0.6"
tiktoken = "^0.8.0"
typing-extensions = "^4.12.2"
typing-inspect = "^0.9.0"
uvicorn = "^0.32.1"
python-dotenv = "^1.0.1"
toml = "^0.10.2"
pillow = "^11.1.0"
python-multipart = "^0.0.19"
gradio = "^5.8.0"
litellm = "^1.53.7"
tenacity = "^9.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-mock = "^3.14.0"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["tests/*"]