[tool.poetry]
name = "haiven"
version = "0.1.0"
description = ""
authors = ["Thoughtworks <haiven@thoughtworks.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
Authlib = "^1.6.3"
boto3 = "^1.40.26"
faiss-cpu = "^1.12.0"
fastapi = "^0.116.1"
google-cloud-aiplatform = "^1.111.0"
google-cloud-firestore = "^2.21.0"
itsdangerous = "^2.2.0"
Jinja2 = "^3.1.6"
langchain = "^0.3.27"
langchain-openai = "^0.3.32"
langchain-community = "^0.3.29"
loguru = "^0.7.3"
ollama = "^0.5.3"
openai = "^1.107.0"
pyarrow = "^21.0.0"
pypdf = "^6.0.0"
python-frontmatter = "^1.1.0"
shapely = "^2.1.1"
tiktoken = "^0.11.0"
typing-extensions = "^4.15.0"
typing-inspect = "^0.9.0"
uvicorn = "^0.35.0"
python-dotenv = "^1.1.1"
toml = "^0.10.2"
pillow = "^11.3.0"
python-multipart = "^0.0.20"
litellm = "^1.76.3"
tenacity = "^9.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-mock = "^3.15.0"
pytest-cov = "^6.3.0"
ragas = "^0.3.3"
langchain-aws="^0.2.31"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = ["tests/*"]